# Generated by Django 2.0.4 on 2018-06-13 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_test', '0002_auto_20180613_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_results', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
