# Generated by Django 2.0.4 on 2018-06-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_test', '0003_quizresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_number',
            field=models.IntegerField(default=20, help_text='Number of questions which are served to user'),
        ),
    ]
