version: '3.5'


services:
  app:
    build: .
    ports:
      - "8891:80"
    depends_on:
      - "db"
    volumes:
      - .:/app
    command:
      gunicorn geo_test.wsgi --bind 0.0.0.0:80 --workers 2 --worker-class gevent --access-logfile=-
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  db:
    image: kartoza/postgis:9.5-2.2
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DBNAME: geo_test
      ALLOW_IP_RANGE: 0.0.0.0/0